// This is an autogenerated file from Firebase Studio.

import { initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  "projectId": "studio-9640881306-b4654",
  "appId": "1:1048562187397:web:c00b05c80cdc10b7af7dec",
  "apiKey": "AIzaSyDCVdPooIaEJ2J8acLf96i_oN4ZmMPgH38",
  "authDomain": "studio-9640881306-b4654.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "1048562187397"
};

const app = initializeApp(firebaseConfig);
export const firestore = getFirestore(app);
